name: tutorial-geoparsing-py39
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.8
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=5.0.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - catalogue=2.0.8
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfitsio=3.470
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.5
  - cryptography=37.0.4
  - cudatoolkit=11.1.1
  - curl=7.83.1
  - cymem=2.0.6
  - cython-blis=0.7.8
  - dataclasses=0.8
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - emoji=2.1.0
  - entrypoints=0.4
  - executing=1.1.0
  - expat=2.4.9
  - fiona=1.8.21
  - flit-core=3.7.1
  - freexl=1.0.6
  - gdal=3.4.1
  - geos=3.8.0
  - geotiff=1.7.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=68.2
  - idna=3.4
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - intel-openmp=2022.1.0
  - ipykernel=6.16.0
  - ipython=8.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.3.5
  - jupyter_console=6.4.4
  - jupyter_core=4.11.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.3
  - kealib=1.4.14
  - krb5=1.19.3
  - langcodes=3.3.0
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.83.1
  - libdeflate=1.14
  - libffi=3.4.2
  - libgdal=3.4.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.8.1
  - libpng=1.6.38
  - libpq=12.9
  - libprotobuf=3.21.6
  - libsodium=1.0.18
  - libspatialite=4.3.0a
  - libsqlite=3.39.3
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libuv=1.44.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.9.2
  - libzlib=1.2.12
  - lxml=4.9.1
  - lz4-c=1.9.3
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - murmurhash=1.0.8
  - nbclient=0.6.8
  - nbconvert=7.0.0
  - nbconvert-core=7.0.0
  - nbconvert-pandoc=7.0.0
  - nbformat=5.6.1
  - nest-asyncio=1.5.5
  - ninja=1.11.0
  - notebook=6.4.12
  - numpy=1.23.3
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathy=0.6.2
  - pickleshare=0.7.5
  - pip=22.2.2
  - pkgutil-resolve-name=1.3.10
  - preshed=3.0.7
  - proj=6.2.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.31
  - prompt_toolkit=3.0.31
  - protobuf=4.21.6
  - psutil=5.9.2
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=1.9.2
  - pygments=2.13.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.9
  - pytorch=1.8.1
  - pywin32=303
  - pywinpty=2.0.8
  - pyzmq=24.0.1
  - qt=5.12.9
  - qtconsole=5.3.2
  - qtconsole-base=5.3.2
  - qtpy=2.2.0
  - requests=2.28.1
  - send2trash=1.8.0
  - setuptools=65.4.0
  - shapely=1.7.1
  - shellingham=1.5.0
  - six=1.16.0
  - smart_open=5.2.1
  - soupsieve=2.3.2.post1
  - spacy=3.4.1
  - spacy-legacy=3.0.10
  - spacy-loggers=1.0.3
  - sqlite=3.39.3
  - srsly=2.4.4
  - stack_data=0.5.1
  - stanza=1.4.2
  - tbb=2021.6.0
  - terminado=0.15.0
  - thinc=8.1.0
  - tiledb=2.11.3
  - tinycss2=1.1.1
  - tk=8.6.12
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.4.0
  - typer=0.4.2
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022d
  - ucrt=10.0.20348.0
  - urllib3=1.26.11
  - vc=14.2
  - vs2015_runtime=14.29.30139
  - wasabi=0.9.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=4.0.3
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xerces-c=3.2.3
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - branca==0.5.0
    - contourpy==1.0.5
    - cycler==0.11.0
    - folium==0.12.1.post1
    - fonttools==4.37.3
    - geojson==2.5.0
    - geopandas==0.11.1
    - gpxpy==1.5.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - matplotlib==3.6.0
    - pandas==1.5.0
    - perdido==0.1.27
    - pillow==9.2.0
    - pyproj==3.4.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pytz==2022.2.1
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - threadpoolctl==3.1.0
